# Generated by Django 5.1.1 on 2024-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0002_class_remove_student_class_student_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
