# Generated by Django 5.1.1 on 2024-09-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0004_alter_student_options_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeform.student'),
        ),
    ]
