# Generated by Django 5.1.1 on 2024-09-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0005_alter_fees_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
