# Generated by Django 5.1.1 on 2024-09-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0006_delete_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeform.class')),
            ],
        ),
    ]
