# Generated by Django 5.1.1 on 2024-09-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0007_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='Classs',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='name',
        ),
        migrations.AddField(
            model_name='fees',
            name='due_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='collegeform.student'),
        ),
        migrations.AddField(
            model_name='fees',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
