# Generated by Django 5.1.1 on 2024-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0008_remove_fees_classs_remove_fees_name_fees_due_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='student',
        ),
    ]
