# Generated by Django 5.1.1 on 2024-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0009_remove_fees_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='collegeform.student'),
        ),
    ]
