# Generated by Django 5.1.1 on 2024-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0010_fees_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
