# Generated by Django 5.1.1 on 2024-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0011_alter_fees_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
