# Generated by Django 5.1.1 on 2024-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeform', '0012_alter_fees_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=False, null=False),
        ),
    ]
